language: php

sudo: false

env:
- WP_VERSION=trunk WP_MULTISITE=0
- WP_VERSION=tags/4.4 WP_MULTISITE=0
- WP_VERSION=tags/4.9 WP_MULTISITE=0
- WP_TRAVISCI=travis:phpunit

matrix:
  allow_failures:
    - env: WP_VERSION=trunk WP_MULTISITE=0
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1    
    - php: 7.2

before_install:
  - composer self-update
  - composer install --no-interaction
  # set up WP install
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR

before_script:
- |
  # Remove Xdebug for a huge performance increase:
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  # Export Composer's global bin dir to PATH, but not on PHP 5.2:
  composer config --list --global
  export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
    case "$TRAVIS_PHP_VERSION" in
      7.2|7.1|7.0|nightly)
        echo "Using PHPUnit 6.x"
        composer global require "phpunit/phpunit:^6"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.x"
        composer global require "phpunit/phpunit:^4"
        ;;
    esac
  fi
  # download WP
- cd $WP_DEVELOP_DIR/..
- rm -rf wordpress
- mkdir wordpress
- svn co https://develop.svn.wordpress.org/$WP_VERSION $WP_DEVELOP_DIR
# set up tests config
- cd $WP_DEVELOP_DIR
- echo $WP_DEVELOP_DIR
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
- sed -i "s/yourusernamehere/root/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
# set up database
- mysql -e 'CREATE DATABASE wordpress_test;' -uroot
- cd $TRAVIS_BUILD_DIR

script:
- |
  if [[ "$TRAVIS_PHP_VERSION" == "7.2" && "$WP_VERSION" == "4.9"  ]] ; then
    phpunit --coverage-clover=coverage.clover
  else
    phpunit
  fi
after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 3

branches:
  only:
  - master

notifications:
  slack:
    rooms:
      - ironbounddesigns:fXMBlqSr9vvDBiwetLNm9ctD#general

    on_success: change
    on_failure: always
    on_start: never
  email: false
